(function() {
  'use strict';

  angular
    .module('angularJsdemo')
    .config(routerConfig);

  /** @ngInject */
  function routerConfig($stateProvider, $urlRouterProvider) {
    $stateProvider
      .state('home', {
        url: '/home',
        templateUrl: 'app/main/main.html',
        controller: 'MainController',
        controllerAs: 'main'
      })
      .state('home.home1',{
        url:'/home1',
        templateUrl:'app/main/home/home1.html',
        controller:'home1Controller'
      })
      .state('home.home2',{
        url:'/home2',
        templateUrl:'app/main/home/home2.html',
        controller:'home2Controller'
      })
      .state('home.home3',{
        url:'/home3',
        templateUrl:'app/main/home/home3.html',
        controller:'home3Controller'
      })
      .state('home.layout',{
        url:'/layout',
        templateUrl:"app/main/layout/layout.html",
        controller:"layoutController"
      })
      .state('home.Echart',{
        url:'/Echart',
        templateUrl:'app/main/chart/Echart.html',
        controller:"EchartController"
      })
      .state('home.D3',{
        url:'/D3',
        templateUrl:'app/main/chart/D3.html',
        controller:'D3Controller'
      })
      .state("home.HighChart",{
        url:'/HighChart',
        templateUrl:'app/main/chart/HighChart.html',
        controller:'HighChartController'
      })
      .state("home.consignee",{
        url:'/consignee',
        templateUrl:'app/main/mail/consignee.html',
        controller:'consigneeController'
      })
      .state("home.outBox",{
        url:'/outBox',
        templateUrl:'app/main/mail/outBox.html',
        controller:'outBoxController'
      })
      .state("home.letterWriting",{
        url:"/letterWriting",
        templateUrl:"app/main/mail/letterWriting.html",
        controller:"letterWritingController"
      })
      .state('home.normalForm',{
        url:'/normalForm',
        templateUrl:'app/main/form/normalForm.html',
        controller:'normalFormController'
      })
      .state("home.normalValidate",{
        url:"/normalValidate",
        templateUrl:'app/main/form/normalValidate',
        controller:'normalValidateController'
      })
      .state("home.advanceForm",{
        url:'/advanceForm',
        templateUrl:'app/main/form/advanceForm.html',
        controller:'advanceFormController'
      })
      .state("home.formGuide",{
        url:'/formGuide',
        templateUrl:'app/main/form/formGuide.html',
        controller:'formGuideController'
      })
      .state("home.upLoadFile",{
        url:'/upLoadFile',
        templateUrl:'app/main/form/upLoadFileController.html',
        controller:'upLoadFileController'
      })
      .state("home.fileEditor",{
        url:'/fileEditor',
        templateUrl:'app/main/form/fileEditor.html',
        controller:'fileEditorController'
      })
      .state("home.autoComplete",{
        url:"/autoComplete",
        templateUrl:'app/main/form/autoComplete.html',
        controller:'autoCompleteController'
      })
      .state("home.datePicker",{
        url:'/datePicker',
        templateUrl:'app/main/form/datePicker.html',
        controller:'datePickerController'
      })
      .state("home.contacts",{
        url:'/contracts',
        templateUrl:'app/main/page/contacts.html',
        controller:'contactsController'
      })
      .state("home.personData",{
        url:'/personData',
        templateUrl:'app/main/page/personData.html',
        controller:'personDataController'
      })
      .state("home.projectManagement",{
        url:'/projectManagement',
        templateUrl:'app/main/page/projectManagement',
        controller:'projectManagementController'
      })
      .state("home.teamManagement",{
        url:'/teamManagement',
        templateUrl:'app/main/page/teamManagement',
        controller:'teamManagementController'
      })
      .state("home.informationFlow",{
        url:'/informationFlow',
        templateUrl:'app/main/page/informationFlow.html',
        controller:'informationFlowController'
      })
      .state("home.customerManagement",{
        url:'/customerManagement',
        templateUrl:'app/main/page/customerManagement.html',
        controller:'customerManagementController'
      })
      .state('home.fileManagement',{
        url:'/fileManagement',
        templateUrl:'app/main/page/fileManagement.html',
        controller:'fileManagementController'
      })
      .state('home.calendar',{
        url:'/calendar',
        templateUrl:'app/main/page/calendar.html',
        controller:'calendarController'
      })
      .state("home.blog",{
        url:'/blog',
        templateUrl:'app/main/page/blog.html',
        controller:'blogController'
      })
      .state("home.FAQ",{
        url:'/FAQ',
        templateUrl:'app/main/page/FAQ.html',
        controller:'FAQController'
      })
      .state("home.timeAxis",{
        url:'/timeAxis',
        templateUrl:'app/main/page/timeAxis.html',
        controller:'timeAxisController'
      })
      .state("home.labelWall",{
        url:'/labelWall',
        templateUrl:'app/main/page/labelWall.html',
        controller:'labelWallController'
      })
      .state("home.ticket",{
        url:'/ticket',
        templateUrl:'app/main/page/ticket.html',
        controller:'ticketController'
      })
      .state("home.searchResult",{
        url:'/searchResult',
        templateUrl:'app/main/page/searchResult.html',
        controller:'searchResultController'
      })
      .state("home.forum",{
        url:'/forum',
        templateUrl:'app/main/page/forum.html',
        controller:'forumController'
      })
      .state("home.IM",{
        url:'/IM',
        templateUrl:'app/main/page/IM.html',
        controller:'IMController'
      })
      .state("home.loginAndRegister",{
        url:'/loginAndRegister',
        templateUrl:'app/main/page/loginAndRegister.html',
        controller:'loginAndRegisterController'
      })
      .state("home.404Page",{
        url:'/404Page',
        templateUrl:'app/main/page/404Page.html',
        controller:'404PageController'
      })
      .state("home.500Page",{
        url:'/500Page',
        templateUrl:'app/main/page/500Page.html',
        controller:'500PageController'
      })





    $urlRouterProvider.otherwise('/home');
  }

})();
